### ISSUE TITLE
Update last gist

### ISSUE THREAD

**Issue by bogdan** [mattn/vim-gist#126]
I am trying to make it easier to create and update gist.
Currently in order to do that I need to publish gist first and than include `GistID` in file.

Is it possible to automatically add `GistID` to current file when publishing with some `:Gist` option or make it possible to update last created gist with current file without including `GistID` ?

**Comment by gabrieljoelc** [comment]
For some reason, I get the "No file name" error when I get to step 4. from https://github.com/mattn/gist-vim/issues/126#issuecomment-19178969. I see that the documentation says "you need to have opened the gist buffer first" but I have been assuming post the gist should do this. What am I missing?
