### ISSUE TITLE
Post failed: Not Found

### ISSUE THREAD

**Issue by benwoodward** [mattn/vim-gist#225]
Just uninstalled, and reinstalled. Deleted `~/.gist-vim`. 

I have 2fa.

When I run `:Gist` I am not prompted to authenticate. I just get the following error: 

![image](https://user-images.githubusercontent.com/1472981/78116455-ce986e00-7460-11ea-8fe1-f47fdc404fef.png)

Using NVIM v0.4.2, MacOS Catalina 10.15.2. 

I have set no gist vim `g:` variables.

**Comment by mattn** [comment]
I don't reproduce this.

**Comment by benwoodward** [comment]
What’s the best way for me to debug this error?

**Comment by benwoodward** [comment]
Resolved the problem. 

[This line of code](https://github.com/mattn/vim-gist/blob/master/autoload/gist.vim#L964) uses the value of `$GITHUB_TOKEN` to authenticate if `g:gist_token` is not set. I have an existing env var by that name for `hub`. I just had to [modify the token's scopes](https://github.com/settings/tokens) to include 'gists' in Github.
