### ISSUE TITLE
Can't setup with 2fa (instead, g:gist_token allow me to complete setup :))

### ISSUE THREAD

**Issue by aiya000** [mattn/vim-gist#230]
My Vim said below after I installed vim-gist then did `:Gist`.

```
Gist.vim requires authorization to use the GitHub API. These settings are stored in "~/.gist-vim". If you want to revoke, do "rm ~/.gist-vim".
GitHub Password for aiya000: <input here with my an access token>
```

```
Gist.vim requires authorization to use the GitHub API. These settings are stored in "~/.gist-vim". If you want to revoke, do "rm ~/.gist-vim".
Not Found
```

I'm using 2fa.
Maybe, it is factor of this.

Instead, my setup is completed with setting `g:gist_token` :tada:

- - -

First, I reported, but alright, I don't want to hurry up to resolve this issue :3

Just I reported for the way to complete setup :)

Thanks!

**Comment by weetabix** [comment]
Thank you, this resolved my issue. Great plugin otherwise.

**Comment by weetabix** [comment]
Additional info: I am not using 2FA in Github, but I did have to pass it the token manually. It would not accept my password, and gave me "Not Found"

**Comment by matthutchinson** [comment]
Same for me

**Comment by mattn** [comment]
First authentication of 2FA is deprecated on GitHub. You need to set below into your `~/.gist-vim`

```
token XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Comment by matthutchinson** [comment]
Thanks, that worked for me

**Comment by chana1024** [comment]
I am not using 2fa,and also had set 'toekn xxxxxxxxxxxx' in ~/.gist-vim.but it still gave me "post faild..."

**Comment by mattn** [comment]
token not toekn.

**Comment by mattn** [comment]
please check permissions of the token.

**Comment by jarun** [comment]
I have @FA set and I had to add the following:

```
user jarun    
token XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Comment by hpsaturn** [comment]
I did a fresh install with Vundle and nothing, the same problem: 

- Gist never ask me for my credentials or run any process for authentication
- Never Gist stored nothing in `.gist-vim`

**The provisional only solution**: 

1. run Vim
2. let g:gist_token = 'ghp_mDsdadxxxxxxxxxxxxxxxxxxxxxxx'
3. Gist -l

**Comment by mattn** [comment]
No. You NEED to store `token XXXXXX` manually into your .gist-vim

**Comment by mattn** [comment]
@jarun Do not add `user` line.

**Comment by mattn** [comment]
I close this issue since most of problems you met are simply mistaking to setup .gist-vim

**Comment by hpsaturn** [comment]
> No. You NEED to store `token XXXXXX` manually into your .gist-vim

sorry, but manually it doesn't works too. I tried everything, the only thing that works is this that I mentioned.

**Comment by mattn** [comment]
Did you check that the token has Gist privileges correctly?

**Comment by hpsaturn** [comment]
well, the token only have one permission in the Github token settings, `gist`, and with it works fine but only when I doing manually like this:

`let g:gist_token = 'ghp_mDsdadxxxxxxxxxxxxxxxxxxxxxxx'`

and the permissions of .gist-vim on my home directory is 644, I need more?
