### ISSUE TITLE
Post failed: (nothing, no reason)

### ISSUE THREAD

**Issue by mjacobus** [mattn/vim-gist#234]
Hey there! I can no longer use vim-gist and I don't know why. It just fails.

![image](https://user-images.githubusercontent.com/226834/135465301-0f7420f8-5f73-4078-be97-9905d70a3b3c.png)

I tried removing ~/.gist-vim to see if I would get an authorization error, but I get the same empty message. I also tried refreshing my token, just to make sure I had not messed it up accidentally. Same message.

Any tips on how to debug this?

Thank you in advance.

**Comment by dantonyuk** [comment]
I have recreated the token and changed `~/.gist-vim`. Not it works like a charm.

Anyway, the error message could be more specific.

**Comment by mjacobus** [comment]
A recent plugin update fixed it, whatever it was. Thank you for sharing @dantonyuk !
